language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: false                      # Don't remove files
  github_token: $GITHUB_PAT               # Set in travis-ci.org dashboard
  local_dir: book-output                  # Deploy the docs folder
  on:
    branch: master

notifications:
  email: false
